steps:
  - name: "gcr.io/cloud-builders/docker"
    args: [
      "build",
      "--build-arg",
      "BUGSNAG_API_KEY=${_BUGSNAG_API_KEY}",
      "--build-arg",
      "GIT_COMMIT=${COMMIT_SHA}",
      "-t",
      "gcr.io/$PROJECT_ID/ingestify:$COMMIT_SHA",
      "."
    ]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/ingestify:$COMMIT_SHA"]
